### ISSUE TITLE
Priorize noarch-packages?

### ISSUE THREAD

**Issue by willirath** [conda-forge/cmocean-feedstock#11]
With the `noarch` packages, I'm seeing
```
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::cmocean-1.1-py27_0
  - conda-forge::cmocean-1.1-py_0
```
and the equivalents of the above for other Python versions.

I assume that this is because the (deprecated?) specific builds are considered equivalent to the `noarch` builds.  Is there a way to fix this?

**Comment by ocefpaf** [comment]
@willirath there is nothing to fix there. It is just a warning and both versions are OK to be installed. Conda will choose one for you also.

Anyways, for cmocean I removed the "Arched" version and left only the `noarch` to avoid that warning.
