### ISSUE TITLE
@conda-forge-admin, please add noarch: python

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/cmocean-feedstock#9]
@conda-forge-admin, please add noarch: python

**Comment by ocefpaf** [comment]
@isuruf it would be nice to expand this action to listen to issues too.
Not sure how difficult that is though.

**Comment by isuruf** [comment]
Hi, I made the recipe noarch: python in conda-forge/cmocean-feedstock#10.

**Comment by ocefpaf** [comment]
:tada:
